# Generated by Django 3.1 on 2020-11-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='status',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccounttype',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entrycomment',
            name='entry_feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='certificationNumber',
            field=models.TextField(null=True),
        ),
    ]
