# Generated by Django 3.1 on 2020-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='inventory',
            new_name='customer_inventory',
        ),
        migrations.AddField(
            model_name='entry',
            name='seller_inventory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
