# Generated by Django 3.1 on 2020-10-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccounttype_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
