# Generated by Django 3.1 on 2020-11-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201118_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycomment',
            name='feedback_time',
            field=models.DateTimeField(null=True),
        ),
    ]
