# Generated by Django 3.1 on 2020-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201019_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='certificationNumber',
            field=models.TextField(null=True),
        ),
    ]
