# Generated by Django 3.1 on 2020-11-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_entrycomment_feedback_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='receiveType',
            field=models.TextField(),
        ),
    ]
