# Generated by Django 3.1 on 2020-11-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201102_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycomment',
            name='feedback_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='entrycomment',
            name='entry_feedback',
            field=models.TextField(null=True),
        ),
    ]
